### ISSUE TITLE
My commits are not shown

### ISSUE THREAD

**Issue by Nerian** [mendicant-original/university-web#112]
The github repo was set 7 days ago, but the new commits are not being shown.

http://university.rubymendicant.com/courses/21/assignments/60/submissions/862

None of my projects show commits :)

**Comment by jordanbyron** [comment]
I have a feeling this has to do with some bad github repositories in the system. I've modified the rake task so it doesn't fail when invalid github repositories are entered into university web. 

Your commits should appear within the next few hours.
