### ISSUE TITLE
Feature: Show irc log history day by day

### ISSUE THREAD

**Issue by edzhelyov** [mendicant-original/university-web#113]
I wanted to see the irc logs from yesterday, so I had to request the full log history and then find where the yesterday logs begin.
The thing that bothers me is that the full history log can become very large and load or crash the browser, so I'm proposing this from that perspective.

Maybe we can paginate the log and have newer/older links for the next pages.

**Comment by practicingruby** [comment]
What we wanted was something like infinite scrolling similar to what Twitter does, but when you scroll up instead of down. Is that something you think you could do?

**Comment by edzhelyov** [comment]
I've done such thing before. We can add this when I start working on university-web. Will discuss it later

**Comment by ericgj** [comment]
fyi, I worked on infinite scrolling for the web dev class, I can send you a link if you want. The code can certainly be improved... it was my first attempt at doing something real in javascript.

**Comment by jordanbyron** [comment]
Closing since this is already in Pivotal Tracker: https://www.pivotaltracker.com/story/show/5631272

If you want to work on this feature please just assign yourself to the ticket. Thanks!
