### ISSUE TITLE
Inflated commit counts on student's assignment pages

### ISSUE THREAD

**Issue by phiggins** [mendicant-original/university-web#119]
For example, before my comment [here](http://university.rubymendicant.com/courses/21/assignments/58/submissions/799#19) on one of the assignments for the current course, I see one commit and a link "Display 312 more like this.". Clicking the link shows more commits, with each legitimate commit duplicated around 15-20 times. Looking at the repo that this assignment refers to, there should only be 4 commits listed.

**Comment by jordanbyron** [comment]
I _think_ I've fixed this issue, but the github commit code needs some serious TLC :)

@coreypurcell please update your github repo in University Web and it should start pulling in your commits for that assignment.

**Comment by phiggins** [comment]
Looks great, thanks Jordan!
