### ISSUE TITLE
submission github repo not saving 

### ISSUE THREAD

**Issue by ericgj** [mendicant-original/university-web#124]
I'm not sure why, but my github repo is not sticking to my submission. Or at least it is not appearing on the [submission page](http://university.rubymendicant.com/courses/22/assignments/63/submissions/878).  The activities log record is created and does appear, but the github repo field remains blank. 

The only thing I can think might be going on is that the first time I saved the submission, I didn't enter a comment; I just clicked 'save' to save the repo name. Also I think I entered the full URL.

**Comment by ericgj** [comment]
or could it be because ericgj/puzzlenode_circuits is > 25 chars and fails validation (not sure why that validation is in there)?

**Comment by jordanbyron** [comment]
@ericgj it was that validation. I too am not sure why it is there. I removed it and re-deployed. Let me know if you still have problems and thanks for the report!
