### ISSUE TITLE
Show-Review page should provide more information about each event

### ISSUE THREAD

**Issue by jamesarosen** [mendicant-original/university-web#29]
See http://img.skitch.com/20101024-mu3kqqpx81t5jfiyxh84j192yh.jpg

Notice that the "commented-on" and "closed" events don't tell you _whose_ review is involved. One option would be to thread the events. Another would be to add the following suffix: `" of #{submitter}'s submission"` or something similar.

**Comment by jordanbyron** [comment]
jamesarosen: Thanks for the feedback. I am in the middle of a complete re-design of the student course pages that should hopefully alleviate this and many other problems with the existing system. You can see some of the progress I've made on that front in this screenshot: http://imgur.com/SsUIu

**Comment by jordanbyron** [comment]
The new submission review system has been merged into master with these fixes.
