### ISSUE TITLE
Allow Clicking on Links in Assignment Notes

### ISSUE THREAD

**Issue by trliner** [mendicant-original/university-web#36]
Currently clicking on a link in the notes section of the Assignment#show view triggers the note editing mode. It would be nice if clicking on the link opened the link.

**Comment by jordanbyron** [comment]
Fixed in commit rmu/university-web@f3c576f4e40524018c56ece2ca622b45ead692d4

Related bugs in CoursesController#show and Courses::Assignments::SubmissionsController#edit fixed in commit rmu/university-web@79fccdae1a3d8920b97a32a7b1b50707f84544ea
