### ISSUE TITLE
RMU homepage menubar not left justified in some linux browsers

### ISSUE THREAD

**Issue by phiggins** [mendicant-original/university-web#41]
Noticed this in Firefox in gentoo, but according to this more things are affected:

http://browsershots.org/http://university.rubymendicant.com/#

**Comment by jordanbyron** [comment]
It looks like the RMU logo is not being floated left. 

I assume you have access to a linux box: Can you install firebug and inspect the logo. Let me know if it is being floated left.

Correct Float: http://i.imgur.com/WpelW.png
No Float: http://imgur.com/Bv5UB

**Comment by phiggins** [comment]
It looks like float is working properly. Here's a screen shot with float on:
http://i.imgur.com/K4xla.png

... and here's with float off:
http://i.imgur.com/ZwrrB.png

**Comment by jordanbyron** [comment]
Ok, try setting the width of the logo div (<div id='logo'...>) to something greater than 650px. 700px or 750px. I have a feeling the width of the font on those systems is making that text flow to the next line creating that strange layout.

**Comment by phiggins** [comment]
Changing the width to 750 fixed it:

http://i.imgur.com/68Hav.png

**Comment by jordanbyron** [comment]
Everything should be rendering correctly now. Let me know if you are still experiencing problems.

**Comment by phiggins** [comment]
Looks good. Thanks Jordan!
