### ISSUE TITLE
Line spacing in code block

### ISSUE THREAD

**Issue by semmons99** [mendicant-original/university-web#43]
![example](http://oi54.tinypic.com/5wwjt3.jpg)

[example](http://oi54.tinypic.com/5wwjt3.jpg)

I believe the line spacing is off a little, notice how "def fetch rate(from, to)" is missing the underscore and the comma looks like a period?

**Comment by jordanbyron** [comment]
Fixed in Commit:  d0533eb892dd8515426332dc42f6b9c80843347a
