### ISSUE TITLE
README Documentation out of date.

### ISSUE THREAD

**Issue by kotp** [mendicant-original/university-web#44]
"To configure University Web:
1. Create a database.yml file in db. The db directory contains an example database.yml for PostgreSQL."

Checked all branches, didn't see a single version.

**Comment by jordanbyron** [comment]
The documentation was incorrect. The `database.yml.example` file is located in the config directory.

This has been fixed in commit: 6e7a8489fbf2bd7ae9ade403b5d72e147bb077d9
