### ISSUE TITLE
IRC logs can load duplicate records

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/university-web#45]
When the server takes +3 seconds to respond to a request, multiple requests are sent to the server. Because the IRC log refresh logic is basic both these requests return the same results, loading duplicate data in the view.

The client should not send another request until the previous one has returned. The client should also display a message if the previous request failed.

**Comment by utkarshkukreti** [comment]
This can be closed. Fixed in [pull-77](https://github.com/rmu/university-web/pull/77).
