### ISSUE TITLE
Make it more clear that "Student notes" is a shared space

### ISSUE THREAD

**Issue by carols10cents** [mendicant-original/university-web#52]
This is about the "Student notes" link in the sidebar on a project.

To me, the singular "Student" implies that it's just for me, one student; but "Students' notes" is a bit awkward. Maybe call this "Group notes"?

Or even just a note when you go to that page that says "this is a shared wiki where any students can add notes about a problem. Please sign your comments when appropriate" or something like that.

**Comment by jordanbyron** [comment]
Ticket created in pivotal:

https://www.pivotaltracker.com/story/show/9689717
