### ISSUE TITLE
Dashboard has only dummy links to Education Reimagined Blog

### ISSUE THREAD

**Issue by smiller** [mendicant-original/university-web#54]
From the Dashboard, on the right-hand side, there are links to the last few articles in the RMU Blog and the last few articles in the Education Reimagined Blog.  The RMU Blog links work.  The Education Reimagined Blog links have the right titles, but dummy link URLs: the current first item in the list is correctly called "link: to really learn quit studying and take a test", but instead of linking to "http://educationreimagined.com/post/2926995382/to-really-learn-quit-studying-and-take-a-test" it links to "http://university.rubymendicant.com/undefined", which opens the default Rails 404 page.

**Comment by jordanbyron** [comment]
Fixed: 76de6f992e46031a8b8a2fcdc4a47d8f8af3cc56
