### ISSUE TITLE
Name Cross-Reference

### ISSUE THREAD

**Issue by ghost** [mendicant-original/university-web#58]
It would be handy to have a cross-reference or lookup for the different names people go by.  Most name fields are in Profile and RMU Directory Name could be added there, as well as a page for each class that lists the students' various names.  The existing lookup on the DIrectory page could be changed to look up on any of the name fields.

**Comment by jordanbyron** [comment]
Moved to Pivotal Tracker

https://www.pivotaltracker.com/story/show/11303613
