### ISSUE TITLE
`rake users:import` is broken

### ISSUE THREAD

**Issue by utkarshkukreti** [mendicant-original/university-web#66]
:github_account_name seems to be a required field on the User model now, which is making the rake task `users:import` silently fail.

**Comment by jordanbyron** [comment]
This rake task was created to initially import users into the application. If you'd like, you can remove it or fix it and send over a pull request.

**Comment by jordanbyron** [comment]
Fixed: bf0a86ce8340db4aecb9b8d574c01048b6006060
