### ISSUE TITLE
Appropriate error message should be shown when uploading a non-zip file at admission page

### ISSUE THREAD

**Issue by thyrlian** [mendicant-original/university-web#80]
Reproduce Steps:
1. Go to admission page: http://university.rubymendicant.com/admissions
2. Fill all fields with correct information
3. Select a non-zip file for source code uploading
4. Click "Submit Application"

Expected Results:
1. If file to be uploaded is a compressed file like tar or rar instead of zip, then it should be successful.
2. If file to be uploaded isn't a compressed file at all, then proper error should be prompted instead of general ambiguous message.

Actual Results:
An error message is displayed "We're sorry, but something went wrong.  We've been notified about this issue and we'll take a look at it shortly."

**Comment by jordanbyron** [comment]
Thanks for the error report. Tests have been added and the error fixed.
