### ISSUE TITLE
Mandatory field validation should be applied for admission page

### ISSUE THREAD

**Issue by thyrlian** [mendicant-original/university-web#81]
Reproduce Steps:
1. Go to admission page: http://university.rubymendicant.com/admissions
2. Leave one or more mandatory fields empty
3. Click "Submit Application"

Expected Results:
Mandatory field validation should be applied for admission page.  A proper error should be displayed just under "Submit Application" button and all empty required fileds should also have some red colored hints nearby.

Actual Results:
An ambiguous error "We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly." is given and page is redirected to http://university.rubymendicant.com/admissions/submissions
This also makes the just filled information lost, thus user has to type again.

**Comment by jordanbyron** [comment]
Thanks for the error report. Tests have been added and the error fixed.
