### ISSUE TITLE
The backgroud description names of some fileds' have a corrupt shift than their textbox after field validation fails at signup page

### ISSUE THREAD

**Issue by thyrlian** [mendicant-original/university-web#85]
Reproduce Steps:
1. Go to admission page: http://university.rubymendicant.com/admissions
2. Leave all fields empty
3. Click "Submit Application"

Expected Results:
Error information for invalid fields appears just at top right of the page.  All fields with their backgroud description name should be well arranged to display.

Actual Results:
The backgroud description names of some fileds' ("Email", "Password", "Github name") have a corrupt shift than their textbox.

**Comment by jordanbyron** [comment]
Fixed: 2ae46ce91fb3b26c40b217ad0dcf44805ba2bbfc

Thanks for the report
